#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D ColorImageOut;
layout(r32f, binding = 1) uniform image2D HistoryImageOut;
layout(r32f, binding = 2) uniform image2D DepthImageOut;
layout(rgba8, binding = 3) uniform image2D AlbedoImageOut;
layout(rgba8i, binding = 4) uniform iimage2D NormalImageOut;
layout(r32f, binding = 5) uniform image2D EmissionImageOut;
layout(r32f, binding = 6) uniform image2D RoughnessImageOut;

uniform sampler2D LastFrameTex;
uniform sampler2D HistoryTex;
uniform sampler2D LastDepthTex;
uniform isampler2D LastNormalTex;
uniform sampler2D LastRoughnessTex;

uniform uvec2 Resolution;
uniform uint FrameCount;

uniform uvec3 MapSize;

uniform mat4 CamRotation;
uniform vec3 CamPosition;

uniform mat4 LastCamRotation;
uniform vec3 LastCamPosition;

uniform usampler2D BrickMap;

uniform usampler2DArray BricksTex;
uniform usampler2D MatsTex;

uniform vec3 EnvironmentColor;
uniform float SunStrength;
uniform float SunAngle;

vec3 SunDirection;

#define BRICK_RES 8
#define EPSILON 0.00001
#define SAMPLES 1.
#define MAX_BOUNCES 3

uint ns;
#define INIT_RNG(coord, res, frame) ns = frame*uint(res.x*res.y+529148401u) + uint((0.5*coord.x+0.5)*res.x+(0.5*coord.y+0.5)*res.x*res.y)

// PCG Random Number Generator
void pcg() {
	uint state = ns * 747796405U + 2891336453U;
	uint word = ((state >> ((state >> 28U) + 4U)) ^ state) * 277803737U;
	ns = (word >> 22U) ^ word;
}

// Random Floating-Point Scalars/Vectors
float rand() {
	pcg();
	return float(ns) / float(0xffffffffU);
}
vec2 rand2() {
	return vec2(rand(), rand());
}
vec3 rand3() {
	return vec3(rand(), rand(), rand());
}
vec4 rand4() {
	return vec4(rand(), rand(), rand(), rand());
}

vec3 CosWeightedRandomHemisphereDirection(const vec3 n) {
	vec2 r = rand2();
	vec3 uu = normalize(cross(n, vec3(0.0, 1.0, 1.0)));
	vec3 vv = cross(uu, n);
	float ra = sqrt(r.y);
	float rx = ra * cos(6.2831 * r.x);
	float ry = ra * sin(6.2831 * r.x);
	float rz = sqrt(1.0 - r.y);
	vec3 rr = vec3(rx * uu + ry * vv + rz * n);
	return normalize(rr);
}

vec3 RandomPointInCircle(const vec3 n){
	vec3 uu = normalize(cross(n, vec3(0.0, 1.0, 1.0)));
	vec3 vv = cross(uu, n);

	float t = 2.0 * 3.14159 * rand();
	float r = rand() + rand();
	if(r > 1.)
		r = 2.0 - r;
	
	return r*(uu * cos(t) + vv * sin(t));
}

struct Ray {
	vec3 origin;
	vec3 dir;
	vec3 inverse_dir;
};

struct Material {
	vec3 color;
	float roughness;
	float emission;
};

uint GetBrickMapCell(ivec3 loc) {
	uint row = texelFetch(BrickMap, ivec2(loc.x * int(MapSize.y) / 8 + loc.y / 8, loc.z), 0).r;
	return (row >> (loc.y % 8) * 4) & 0xFu;
}

uint GetBrickCell(int brick, ivec3 loc) {
	uint row = texelFetch(BricksTex, ivec3(loc.x * BRICK_RES / 8 + loc.y / 8, loc.z, brick - 1), 0).r;
	return (row >> (loc.y % 8) * 4) & 0xFu;
}

Material GetMaterial(int brickIndex, int matIndex) {
	uvec4 val = texelFetch(MatsTex, ivec2(matIndex, brickIndex), 0);
	vec3 color = vec3(float((val.r >> 16) & 0xFFu) / 255., float((val.r >> 8) & 0xFFu) / 255., float((val.r >> 0) & 0xFFu) / 255.);
	float emission = (val.g & 0xFFFFu) / 50.;
	float roughness = float(val.r >> 24) / 255.;
	return Material(color, roughness, emission);
}

vec3 GetSky(vec3 dir) {
	if(EnvironmentColor != vec3(-1))
		return EnvironmentColor;

	vec3 sky = clamp(exp2(-dir.y / vec3(.35, .45, .6)), 0., 1.);
	vec3 sun = clamp(pow(dot(SunDirection, dir), 700), 0., 1.) * vec3(1., 0.8, 0.4);

	return sky + sun;
}

vec4 TestBrick(int brick, vec2 coords) {
	if(coords.y > 0.)
		return vec4(GetBrickCell(brick, ivec3(int(fract(coords.x * 4. + 4.) * 8.), int(coords.y * 32.), int(coords.x * 4. + 4.))) / 8.);
	else if(coords.y > -1 / 4.)
		return vec4(int(fract(coords.x * 4. + 4.) * 8.) / 8., int(coords.y * 32. + 8.) / 8., int(coords.x * 4. + 4.) / 8., 1.);
	else
		return vec4(0.);
}

struct SlabIntersection {
	bool hit;
	float tmin;
	float tmax;
	bvec3 normal;
};

SlabIntersection RaySlabIntersection(Ray ray, vec3 minpos, vec3 maxpos) {
	vec3 tbot = ray.inverse_dir * (minpos - ray.origin);
	vec3 ttop = ray.inverse_dir * (maxpos - ray.origin);

	vec3 dmin = min(ttop, tbot);
	vec3 dmax = max(ttop, tbot);

	float tmin = max(max(dmin.x, dmin.y), dmin.z);
	float tmax = min(min(dmax.x, dmax.y), dmax.z);

	bvec3 normal = equal(dmin, vec3(tmin));

	return SlabIntersection(tmax > max(tmin, 0.0), tmin, tmax, normal);
}

struct GridHit {
	bool hit;
	float dist;
	ivec3 normal;
	Material mat;
	int additional;
};

// J. Amanatides, A. Woo. A Fast Voxel Traversal Algorithm for Ray Tracing.
GridHit RayBrickIntersection(Ray ray, int brickIndex, vec3 gridPos, float gridScale) {
	GridHit noHit = GridHit(false, -1., ivec3(-1), Material(vec3(0.), 0., 0.), 0);

	SlabIntersection boundHit = RaySlabIntersection(ray, gridPos, gridPos + vec3(gridScale));
	if(!boundHit.hit)
		return noHit;

	float tMin = boundHit.tmin;
	float tMax = boundHit.tmax;

	vec3 ray_start = ray.origin + ray.dir * tMin - gridPos;
	if(tMin < 0.)
		ray_start = ray.origin - gridPos;
	vec3 ray_end = ray.origin + ray.dir * tMax - gridPos;

	float voxel_size = gridScale / BRICK_RES;

	ivec3 curr_voxel = max(min(ivec3((ray_start) / voxel_size), ivec3(BRICK_RES - 1)), ivec3(0));
	ivec3 last_voxel = max(min(ivec3((ray_end) / voxel_size), ivec3(BRICK_RES - 1)), ivec3(0));

	ivec3 step = ivec3(sign(ray.dir));

	vec3 t_next = ((curr_voxel + max(step, ivec3(0))) * voxel_size - ray_start) * ray.inverse_dir;
	vec3 t_delta = voxel_size * abs(ray.inverse_dir);

	float dist = 0.;
	bvec3 mask = boundHit.normal;

	int iter = 0;
	while(last_voxel != curr_voxel && iter++ < BRICK_RES * 4) {
		uint cell = GetBrickCell(brickIndex, curr_voxel);
		if(cell != 0u)
			return GridHit(true, dist + max(tMin, 0.), -ivec3(mask) * step, GetMaterial(brickIndex - 1, int(cell)), iter);

		mask = lessThanEqual(t_next.xyz, min(t_next.yzx, t_next.zxy));

		dist = min(min(t_next.x, t_next.y), t_next.z);
		t_next += vec3(mask) * t_delta;
		curr_voxel += ivec3(mask) * step;
	}

	uint cell = GetBrickCell(brickIndex, curr_voxel);
	if(cell != 0u)
		return GridHit(true, dist + max(tMin, 0.), -ivec3(mask) * step, GetMaterial(brickIndex - 1, int(cell)), iter);

	noHit.additional = iter;
	return noHit;
}

GridHit RaySceneIntersection(Ray ray, vec3 gridPos, float gridScale, int limit) {
	GridHit noHit = GridHit(false, -1., ivec3(-1), Material(vec3(0.), 0., 0.), 0);

	SlabIntersection boundHit = RaySlabIntersection(ray, gridPos, gridPos + MapSize * gridScale);
	if(!boundHit.hit)
		return noHit;

	float tMin = boundHit.tmin;
	float tMax = boundHit.tmax;

	vec3 ray_start = ray.origin + ray.dir * tMin - gridPos;
	if(tMin < 0.)
		ray_start = ray.origin - gridPos;
	vec3 ray_end = ray.origin + ray.dir * tMax - gridPos;

	float voxel_size = gridScale;

	ivec3 curr_voxel = max(min(ivec3((ray_start) / voxel_size), ivec3(MapSize) - ivec3(1)), ivec3(0));
	ivec3 last_voxel = max(min(ivec3((ray_end) / voxel_size), ivec3(MapSize) - ivec3(1)), ivec3(0));

	ivec3 step = ivec3(sign(ray.dir));

	vec3 t_next = ((curr_voxel + max(step, ivec3(0))) * voxel_size - ray_start) * ray.inverse_dir;
	vec3 t_delta = voxel_size * abs(ray.inverse_dir);

	bvec3 mask;

	int iter = 0, brickIter = 0;
	while(last_voxel != curr_voxel && iter++ < limit) {
		uint cell = GetBrickMapCell(curr_voxel);
		if(cell != 0u) {
			GridHit hit = RayBrickIntersection(ray, int(cell), gridPos + curr_voxel * gridScale, gridScale);
			brickIter += hit.additional;
			if(hit.hit)
				return GridHit(true, hit.dist, hit.normal, hit.mat, iter + brickIter);
		}

		mask = lessThanEqual(t_next.xyz, min(t_next.yzx, t_next.zxy));

		t_next += vec3(mask) * t_delta;
		curr_voxel += ivec3(mask) * step;
	}

	uint cell = GetBrickMapCell(curr_voxel);
	if(cell != 0u) {
		GridHit hit = RayBrickIntersection(ray, int(cell), gridPos + curr_voxel * gridScale, gridScale);
		brickIter += hit.additional;
		if(hit.hit)
			return GridHit(true, hit.dist, hit.normal, hit.mat, iter + brickIter);
	}

	noHit.additional = iter + brickIter;
	if(iter == limit + 1)
		noHit.dist = 0.;
	return noHit;
}

vec3 Trace(Ray ray, GridHit firstHit) {
	float sunChance = 1. - 1. / pow(SunStrength + 1., 0.1);
	vec3 rayColor = vec3(1.);
	vec3 incomingLight = vec3(0.);

	int limit = int(MapSize.x + MapSize.y + MapSize.z);
	for(int i = 0; i <= MAX_BOUNCES; i++) {
		GridHit hitInfo;
		if(i == 0)
			hitInfo = firstHit;
		else
			hitInfo = RaySceneIntersection(ray, vec3(0.), 1., limit);

		if(!hitInfo.hit) {
			if(hitInfo.dist < 0.){
				return incomingLight + rayColor * GetSky(ray.dir);
			}
			return vec3(0.);
		}

		if(i != 0) {
			rayColor *= hitInfo.mat.color;
			incomingLight += rayColor * hitInfo.mat.emission;
		}

		ray.origin += ray.dir * hitInfo.dist + hitInfo.normal * EPSILON;

		if (rand() < sunChance*pow(hitInfo.mat.roughness, 3)){ // sun ray
			vec3 lastdir = ray.dir;

			ray.dir = normalize(SunDirection + 0.02*RandomPointInCircle(SunDirection));
			ray.inverse_dir = 1.0 / ray.dir;

			if (!RaySceneIntersection(ray, vec3(0.), 1., int(MapSize.x + MapSize.y + MapSize.z)).hit) return incomingLight + rayColor * vec3(SunStrength);

			ray.dir = lastdir;
		}

		vec3 diffuseDir = CosWeightedRandomHemisphereDirection(hitInfo.normal);

		vec3 specularDir = reflect(ray.dir, vec3(hitInfo.normal));

		ray.dir = normalize(mix(specularDir, diffuseDir, hitInfo.mat.roughness));

		ray.inverse_dir = 1.0 / ray.dir;

		limit = int(pow(limit, max(0.87, 1. / (i + 1))));
	}

	return incomingLight;
}

float RaySphereIntersection(Ray ray, vec3 pos, float radius) {
	vec3 origin = ray.origin - pos;

	float a = dot(ray.dir, ray.dir);
	float b = 2 * dot(origin, ray.dir);
	float c = dot(origin, origin) - radius * radius;

	float discriminant = b * b - 4 * a * c;

	if(discriminant < 0)
		return -1.;

	return (-b - sqrt(discriminant)) / (2 * a);
}

vec2 WorldToLastScreenCoord(vec3 p) {
	vec3 dir = normalize(p - LastCamPosition);

	vec3 localNearPlane = (transpose(LastCamRotation) * vec4(dir, 0.)).xyz;
	vec2 texCoord = (localNearPlane.xy / localNearPlane.z * 1.5) / vec2(float(Resolution.x) / float(Resolution.y), 1.);

	return texCoord;
}

uniform vec3[] offsets = vec3[](vec3(0.), vec3(1., 0., 0.), vec3(-1., 0., 0.), vec3(0., 1., 0.), vec3(0., -1., 0.), vec3(0., 0., 1.), vec3(0., 0., -1.), vec3(1., 1., 0.), vec3(-1., 1., 0.), vec3(-1., 1., 0.), vec3(-1., -1., 0.), vec3(0., 1., 1.), vec3(0., -1., 1.), vec3(0., -1., 1.), vec3(0., -1., -1.), vec3(1., 0., 1.), vec3(-1., 0., 1.), vec3(-1., 0., 1.), vec3(-1., 0., -1.), vec3(2., 0., 0.), vec3(-2., 0., 0.), vec3(0., 2., 0.), vec3(0., -2., 0.), vec3(0., 0., 2.), vec3(0., 0., -2.));

struct SamplePoint {
	float dist;
	float history;
	vec3 color;
	float accuracy;
};

SamplePoint FindBestSample(GridHit hit, Ray ray) {
	if(!hit.hit)
		return SamplePoint(100., 0., vec3(0.), 0.);

	vec3 hitPos = CamPosition + hit.dist * ray.dir;

	vec3 normalPlane = vec3(1.) - abs(hit.normal);

	float bestDist = 100.;
	vec2 bestCoord = vec2(0.);

	vec3 colorSum = vec3(0.);
	float matchCount = 0.;

	for(int i = 0; i < offsets.length(); i++) {
		if(normalPlane * offsets[i] != offsets[i])
			continue;

		vec3 currPos = hitPos + offsets[i] * 0.02;
		vec2 currCoord = WorldToLastScreenCoord(currPos) * 0.5 + 0.5;

		vec3 actualPos = LastCamPosition + normalize(currPos - LastCamPosition) * texture(LastDepthTex, currCoord, 0).r;
		float dist = distance(hitPos, actualPos);
		ivec3 normal = texture(LastNormalTex, currCoord, 0).rgb;
		float roughness = texture(LastRoughnessTex, currCoord, 0).r;

		if(normal == hit.normal) {
			float value = dist * mix(1., pow(abs(texture(LastRoughnessTex, currCoord, 0).r - hit.mat.roughness), 0.3), 0.2);
			if(value < bestDist) {
				bestDist = value;
				bestCoord = currCoord;
			}

			float maxDist = 0.08;
			float weight = pow(max(maxDist - dist, 0.) / maxDist, 4.) * pow(1. - abs(roughness - hit.mat.roughness), 2.);

			colorSum += weight * texture(LastFrameTex, currCoord).rgb;
			matchCount += weight;
		}
	}

	float accuracy = 1. - pow(abs(texture(LastRoughnessTex, bestCoord, 0).r - hit.mat.roughness), 0.5);

	vec2 lastScreenPos = WorldToLastScreenCoord(hitPos);
	if(min(max(lastScreenPos, vec2(-1.)), vec2(1.)) != lastScreenPos)
		accuracy = pow(hit.mat.roughness, 5.);

	if(bestDist > 0.1)
		accuracy = 0.;

	float history = texelFetch(HistoryTex, ivec2(bestCoord * Resolution), 0).r;

	float weight = mix(0.85, 1., min(history / 200., 1.));
	if(hit.mat.roughness < 1.)
		weight = mix(weight, 1., 0.97);

	if (matchCount == 0.) matchCount = 1.;

	return SamplePoint(bestDist, history, mix(colorSum / matchCount, texture(LastFrameTex, bestCoord).rgb, weight), accuracy);
}

void main() {
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = vec2(gl_GlobalInvocationID.xy)/gl_NumWorkGroups.xy * 2. - vec2(1.);
	INIT_RNG(uv, Resolution, FrameCount);
	SunDirection = normalize(vec3(0.6 * cos(SunAngle/360.*6.2831), 1.0, 0.6 * sin(SunAngle/ 360. * 6.2831)));

	float aspect = float(Resolution.x) / float(Resolution.y);

	vec3 localNearPlane = vec3(uv.x * aspect, uv.y, 1.5);

	vec3 firstDir = normalize((CamRotation * vec4(localNearPlane, 0.)).xyz);
	Ray firstRay = Ray(CamPosition, firstDir, 1.0 / firstDir);
	GridHit firstHit = RaySceneIntersection(firstRay, vec3(0.), 1., int(MapSize.x + MapSize.y + MapSize.z));

	imageStore(DepthImageOut, texelCoord, vec4(firstHit.dist));
	imageStore(NormalImageOut, texelCoord, ivec4(firstHit.normal, 0));

	if(!firstHit.hit) {
		imageStore(ColorImageOut, texelCoord, vec4(GetSky(firstDir), 0.));
		imageStore(EmissionImageOut, texelCoord, vec4(-1.));
		imageStore(RoughnessImageOut, texelCoord, vec4(0.));
		imageStore(HistoryImageOut, texelCoord, vec4(0.));
		imageStore(AlbedoImageOut, texelCoord, vec4(0.));
		return;
	}

	vec3 sumColor = vec3(0.);
	for(int s = 0; s < SAMPLES; s++) {
		vec3 offset = vec3(2. * rand2() - 1., 0.) / Resolution.y; // for anti aliasing

		sumColor += Trace(firstRay, firstHit);
	}

	vec3 color = sumColor / SAMPLES;

	// spatiotemporal denoisification
	SamplePoint samplePoint = FindBestSample(firstHit, firstRay);

	float historyScale = (1. - samplePoint.dist * 1.5) * samplePoint.accuracy;
	if(LastCamPosition != CamPosition)
		historyScale *= pow(firstHit.mat.roughness, 0.12);

	float history = samplePoint.history * historyScale + 1.;
	if(LastCamPosition != CamPosition)
		history = min(history, 1. + firstHit.mat.roughness * 200.);

	vec3 albedo;
	if(firstHit.hit)
		albedo = firstHit.mat.color;
	else
		albedo = vec3(1.);

  imageStore(ColorImageOut, texelCoord, vec4(mix(samplePoint.color, color, 1.0 / (pow(history, 0.97))), 0.));
	
	imageStore(AlbedoImageOut, texelCoord, vec4(albedo, 0.));
	imageStore(HistoryImageOut, texelCoord, vec4(history));
	imageStore(EmissionImageOut, texelCoord, vec4(firstHit.mat.emission));
	imageStore(RoughnessImageOut, texelCoord, vec4(firstHit.mat.roughness));

	return;
}